name:                quivela
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Daniel Schoepe and Sean McLaughlin"
maintainer:          ""
copyright:           "2018 AWS Labs"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/quivela#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Quivela
  - Quivela.Diff
  - Quivela.Language
  - Quivela.Parse
  - Quivela.QuasiQuote
  - Quivela.SymEval
  - Quivela.Util
  - Quivela.Verify
  ghc-options:
  - -fwarn-incomplete-patterns
  other-modules:
  - Quivela.VerifyPreludes
  - System.Timer
  dependencies:
  - HUnit
  - array
  - bytestring
  - cereal
  - cond
  - containers
  - deepseq
  - directory
  - filepath
  - lens
  - mtl
  - parsec
  - process
  - syb
  - template-haskell
  - temporary
  - time

tests:
  quivela-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - containers
    - deepseq
    - quivela
