name:                quivela
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Daniel Schoepe and Sean McLaughlin"
maintainer:          ""
copyright:           "2018 AWS Labs"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/quivela#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - NoImplicitPrelude

library:
  source-dirs: src
  exposed-modules:
  - Quivela
  - Quivela.Diff
  - Quivela.Language
  - Quivela.Parse
  - Quivela.Pretty
  - Quivela.QuasiQuote
  - Quivela.SymEval
  - Quivela.Util
  - Quivela.Verify
  - Quivela.Z3
  ghc-options:
  - -Werror
  - -Weverything
  - -Wno-missing-import-lists # This is too painful
  - -Wno-missing-local-signatures # This is too painful
  - -Wno-unsafe # Template Haskell and Serializable
  - -Wno-safe # Not sure what this is, and failing on System.Timer
  - -Wno-all-missed-specialisations # We don't want to add noisy INLINABLE pragmas as we aren't peformance sensitive
  - -Wno-missed-specialisations # We don't want to add noisy INLINABLE pragmas as we aren't peformance sensitive
  other-modules:
  - Quivela.Prelude
  - Quivela.Resources
  - Quivela.VerifyPreludes
  - System.Timer
  dependencies:
  - HUnit
  - array
  - bytestring
  - cereal
  - cond
  - containers
  - deepseq
  - directory
  - file-embed
  - filepath
  - lens
  - mtl
  - parsec
  - pretty
  - prettyprinter
  - process
  - smtLib
  - syb
  - template-haskell
  - temporary
  - time

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - containers
    - deepseq
    - lens
    - quivela
  cpp-example:
    main: examples/CppExample.hs
    dependencies:
    - quivela
  envelope:
    main: examples/Envelope.hs
    dependencies:
    - lens
    - quivela
  envelope-small:
    main: examples/EnvelopeSmall.hs
    dependencies:
    - quivela
  etm:
    main: examples/ETM.hs
    dependencies:
    - quivela
  etm-small:
    main: examples/ETMSmall.hs
    dependencies:
    - quivela
  fifo:
    main: examples/FIFO.hs
    dependencies:
    - quivela
  fifo-small:
    main: examples/FIFOSmall.hs
    dependencies:
    - quivela
